include: ['_css', '_scripts', '_images']

title: Battle Facilities Calculator

github: [metadata]
  
url: "https://will-jj.github.io"
  
repository: eisencalc

description:
  
  

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

theme: jekyll-theme-cayman
