var ABILITIES_ADV = [
	"Air Lock",
	"Battle Armor",
	"Blaze",
	"Chlorophyll",
	"Clear Body",
	"Cloud Nine",
	"Color Change",
	"Compound Eyes",
	"Cute Charm",
	"Drizzle",
	"Damp",
	"Drought",
	"Early Bird",
	"Effect Spore",
	"Flame Body",
	"Flash Fire",
	"Flash Fire (activated)",
	"Forecast",
	"Guts",
	"Huge Power",
	"Hustle",
	"Hyper Cutter",
	"Illuminate",
	"Immunity",
	"Inner Focus",
	"Insomnia",
	"Intimidate",
	"Keen Eye",
	"Levitate",
	"Limber",
	"Liquid Ooze",
	"Magma Armor",
	"Magnet Pull",
	"Marvel Scale",
	"Minus",
	"Natural Cure",
	"Oblivious",
	"Overgrow",
	"Own Tempo",
	"Pickup",
	"Plus",
	"Poison Point",
	"Pressure",
	"Pure Power",
	"Rain Dish",
	"Rough Skin",
	"Sand Stream",
	"Sand Veil",
	"Serene Grace",
	"Shadow Tag",
	"Shed Skin",
	"Shell Armor",
	"Soundproof",
	"Speed Boost",
	"Static",
	"Stench",
	"Sticky Hold",
	"Sturdy",
	"Suction Cups",
	"Swarm",
	"Swift Swim",
	"Synchronize",
	"Thick Fat",
	"Torrent",
	"Trace",
	"Truant",
	"Vital Spirit",
	"Volt Absorb",
	"Water Absorb",
	"Water Veil",
	"White Smoke",
	"Wonder Guard"
];

var ABILITIES_DPP = ABILITIES_ADV.concat([
	"Adaptability",
	"Anger Point",
	"Anticipation",
	"Bad Dreams",
	"Download",
	"Dry Skin",
	"Filter",
	"Flower Gift",
	"Frisk",
	"Gluttony",
	"Heatproof",
	"Honey Gather",
	"Hydration",
	"Ice Body",
	"Iron Fist",
	"Klutz",
	"Leaf Guard",
	"Magic Guard",
	"Mold Breaker",
	"Motor Drive",
	"Multitype",
	"No Guard",
	"Normalize",
	"Poison Heal",
	"Reckless",
	"Rivalry",
	"Scrappy",
	"Simple",
	"Skill Link",
	"Slow Start",
	"Sniper",
	"Snow Cloak",
	"Snow Warning",
	"Solar Power",
	"Solid Rock",
	"Stall",
	"Steadfast",
	"Super Luck",
	"Tangled Feet",
	"Technician",
	"Tinted Lens",
	"Unaware",
	"Unburden"
]);

var ABILITIES_BW = ABILITIES_DPP.concat([
	"Analytic",
	"Big Pecks",
	"Contrary",
	"Cursed Body",
	"Defeatist",
	"Defiant",
	"Flare Boost",
	"Friend Guard",
	"Harvest",
	"Healer",
	"Heavy Metal",
	"Illusion",
	"Imposter",
	"Infiltrator",
	"Iron Barbs",
	"Lightning Rod",
	"Light Metal",
	"Magic Bounce",
	"Moody",
	"Moxie",
	"Multiscale",
	"Mummy",
	"Overcoat",
	"Pickpocket",
	"Prankster",
	"Sand Force",
	"Sand Rush",
	"Sap Sipper",
	"Sheer Force",
	"Storm Drain",
	"Telepathy",
	"Teravolt",
	"Toxic Boost",
	"Turboblaze",
	"Unnerve",
	"Victory Star",
	"Weak Armor",
	"Wonder Skin",
	"Zen Mode"
]);

var ABILITIES_XY = ABILITIES_BW.concat([
	"Aerilate",
	"Aura Break",
	"Aroma Veil",
	"Bulletproof",
	"Cheek Pouch",
	"Competitive",
	"Dark Aura",
	"Delta Stream",
	"Desolate Land",
	"Fairy Aura",
	"Flower Veil",
	"Fur Coat",
	"Gale Wings",
	"Gooey",
	"Magician",
	"Mega Launcher",
	"Parental Bond",
	"Pixilate",
	"Primordial Sea",
	"Protean",
	"Refrigerate",
	"Stance Change",
	"Strong Jaw",
	"Sweet Veil",
	"Symbiosis",
	"Tough Claws"
]);

var ABILITIES_SM = ABILITIES_XY.concat([
	"Battery",
	"Battle Bond",
	"Beast Boost",
	"Berserk",
	"Comatose",
	"Corrosion",
	"Dancer",
	"Dazzling",
	"Disguise",
	"Electric Surge",
	"Emergency Exit",
	"Fluffy",
	"Full Metal Body",
	"Galvanize",
	"Grass Pelt",
	"Grassy Surge",
	"Innards Out",
	"Liquid Voice",
	"Long Reach",
	"Merciless",
	"Misty Surge",
	"Neuroforce",
	"Power Construct",
	"Power of Alchemy",
	"Prism Armor",
	"Psychic Surge",
	"Queenly Majesty",
	"RKS System",
	"Receiver",
	"Schooling",
	"Shadow Shield",
	"Shields Down",
	"Slush Rush",
	"Stamina",
	"Stakeout",
	"Steelworker",
	"Soul-Heart",
	"Surge Surfer",
	"Tangling Hair",
	"Triage",
	"Water Bubble",
	"Water Compaction",
	"Wimp Out"
]);

ABILITIES_XY.splice(ABILITIES_XY.indexOf("Lightningrod"), 1, "Lightning Rod");

var ABILITIES_SS = ABILITIES_SM.concat([
	"As One",
	"Ball Fetch",
	"Chilling Neigh",
	"Cotton Down",
	"Curious Medicine",
	"Dauntless Shield",
	"Dragon's Maw",
	"Gorilla Tactics",
	"Grim Neigh",
	"Gulp Missile",
	"Hunger Switch",
	"Ice Face",
	"Libero",
	"Ice Scales",
	"Intrepid Sword",
	"Mimicry",
	"Mirror Armor",
	"Neutralizing Gas",
	"Pastel Veil",
	"Perish Body",
	"Power Spot",
	"Propeller Tail",
	"Punk Rock",
	"Quick Draw",
	"Ripen",
	"Sand Spit",
	"Screen Cleaner",
	"Stalwart",
	"Steam Engine",
	"Steely Spirit",
	"Transistor",
	"Unseen Fist",
	"Wandering Spirit"
]);
var ABILITIES_SV = ABILITIES_SS.concat([
	"Anger Shell",
	"Armor Tail",
	"Beads of Ruin",
	"Commander",
	"Costar",
	"Cud Chew",
	"Earth Eater",
	"Electromorphosis",
	"Good as Gold",
	"Guard Dog",
	"Hadron Engine",
	"Lingering Aroma",
	"Mycelium Might",
	"Opportunist",
	"Orichalcum Pulse",
	"Protosynthesis",
	"Purifying Salt",
	"Quark Drive",
	"Rocky Payload",
	"Seed Sower",
	"Sharpness",
	"Supreme Overlord",
	"Sword of Ruin",
	"Tablets of Ruin",
	"Thermal Exchange",
	"Toxic Debris",
	"Vessel of Ruin",
	"Well-Baked Body",
	"Wind Power",
	"Wind Rider",
	"Zero to Hero"
]);
